apiVersion: apps.k8smgmt.io/v3
kind: WorkloadTemplate
metadata:
  name: test-git-values-template
  project: vivek
spec:
  artifact:
    artifact:
      chartName: mychart
      chartVersion: 0.1.4
      repository: default-bitnami
      valuesRef:
        repository: default-cert-manager
        revision: main
        valuesPaths:
        - name: ballot-deployment1.yaml
    options:
      maxHistory: 10
      timeout: 5m0s
    type: Helm
